# Generated by Django 4.0.2 on 2022-03-21 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_extrauserinformation_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauserinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='extrauserinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
