# Generated by Django 4.0.2 on 2022-02-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateField(auto_created=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined')], max_length=1)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_listing', to='api.listing')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_item', to='api.listing')),
            ],
        ),
    ]
