# Generated by Django 4.0.2 on 2022-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_listing_location_listing_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
