# Generated by Django 4.0.2 on 2022-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_offer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='offers',
            field=models.ManyToManyField(null=True, to='api.Offer'),
        ),
    ]
