# Generated by Django 4.0.2 on 2022-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_listing_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, to='api.Offer'),
        ),
    ]
