# Generated by Django 4.0.2 on 2022-03-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_listing_image_listing_category_listing_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='offers',
        ),
    ]
