# Generated by Django 4.0.2 on 2022-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_listing_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, to='api.Listing'),
        ),
    ]
