# Generated by Django 4.0.2 on 2022-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_listing_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image2',
            field=models.TextField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image3',
            field=models.TextField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image4',
            field=models.TextField(blank=True, max_length=65000, null=True),
        ),
    ]
